root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ./cmd/sorcerer"
  delay = 1000
  exclude_dir = ["assets", "data", "tmp", "vendor"]
  include_ext = ["go", "tpl", "tmpl", "html"]
