[tools]
go = "1.24"
"go:mvdan.cc/gofumpt" = "latest"
watchexec = "latest"

[tasks.start]
run = "go run ./cmd/sorcerer"
sources = ["**/*.go", "go.mod", "go.sum"]

[tasks.build]
run = "go build -o ./tmp/sorcerer ./cmd/sorcerer"
sources = ["**/*.go", "go.mod", "go.sum"]
outputs = ["./tmp/sorcerer"]

[tasks.dev]
run = "mise watch -r start"

[tasks.fmt]
run = "gofumpt -l -w ."
sources = ["**/*.go"]
