#! /usr/bin/env bash

cd distribution-spec/conformance

go test -c

export OCI_ROOT_URL=http://localhost:3000
export OCI_NAMESPACE=test/conformance
export OCI_CROSSMOUNT_NAMESPACE=test/conformance-crossmount
export OCI_USERNAME=""
export OCI_PASSWORD=""

export OCI_TEST_PULL=1
export OCI_TEST_PUSH=1
export OCI_TEST_CONTENT_DISCOVERY=1
export OCI_TEST_CONTENT_MANAGEMENT=1

export OCI_HIDE_SKIPPED_WORKFLOWS=0
export OCI_DEBUG=1
export OCI_DELETE_MANIFEST_BEFORE_BLOBS=1
export OCI_REPORT_DIR=./reports

./conformance.test
