#! /usr/bin/env bash

#USAGE flag "-o --os <os>" help="The OS to build for" default="linux"
#USAGE flag "-a --arch <arch>" help="The architecture to build for" default="amd64"

#MISE env={ CGO_ENABLED="0" }
#MISE sources=["cmd/**/*.go", "internal/**/*.go", "go.mod", "go.sum"]
#MISE outputs=["./bin/sorcerer-${usage_os}-${usage_arch}"]

go build -o ./bin/sorcerer-${usage_os}-${usage_arch} ./cmd/sorcerer
