#! /usr/bin/env bash

#MISE env={ CGO_ENABLED="0" }
#MISE sources=["cmd/**/*.go", "internal/**/*.go", "go.mod", "go.sum"]
#MISE outputs=["./bin/sorcerer-${GOOS}-${GOARCH}"]

GOOS=${GOOS:-linux}
GOARCH=${GOARCH:-amd64}

go build -o ./bin/sorcerer-${GOOS}-${GOARCH} ./cmd/sorcerer
